spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mkd_dev
    username: mkd_dev_user
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#     javax:
#      persistence:
#        schema-generation:
#          create-source: metadata
#          scripts:
#            action: create
#            create-target: mkd_database_create.sql