spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mkd_prod
    username: mkd_prod_user
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false